# Generated by Django 6.0.6 on 2026-07-03 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_tet', models.CharField(blank=True, max_length=100)),
                ('name_pt', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
            ],
            options={
                'verbose_name_plural': 'News categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=220)),
                ('title_tet', models.CharField(blank=True, max_length=220)),
                ('title_pt', models.CharField(blank=True, max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt_en', models.CharField(blank=True, max_length=300)),
                ('excerpt_tet', models.CharField(blank=True, max_length=300)),
                ('excerpt_pt', models.CharField(blank=True, max_length=300)),
                ('content_en', models.TextField(blank=True)),
                ('content_tet', models.TextField(blank=True)),
                ('content_pt', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.newscategory')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='news_newspo_is_publ_401ce7_idx')],
            },
        ),
    ]
