# Generated by Django 6.0.6 on 2026-07-03 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_name', models.CharField(default='Timor Diagnostics (TDx)', max_length=150)),
                ('short_name', models.CharField(default='TDx', max_length=30)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('tagline_en', models.CharField(blank=True, max_length=220)),
                ('tagline_tet', models.CharField(blank=True, max_length=220)),
                ('tagline_pt', models.CharField(blank=True, max_length=220)),
                ('about_en', models.TextField(blank=True)),
                ('about_tet', models.TextField(blank=True)),
                ('about_pt', models.TextField(blank=True)),
                ('about_secondary_en', models.TextField(blank=True, help_text='Second About paragraph (e.g. bridging public/private gaps).')),
                ('about_secondary_tet', models.TextField(blank=True)),
                ('about_secondary_pt', models.TextField(blank=True)),
                ('vision_en', models.TextField(blank=True)),
                ('vision_tet', models.TextField(blank=True)),
                ('vision_pt', models.TextField(blank=True)),
                ('mission_en', models.TextField(blank=True)),
                ('mission_tet', models.TextField(blank=True)),
                ('mission_pt', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('address_en', models.CharField(blank=True, max_length=255)),
                ('address_tet', models.CharField(blank=True, max_length=255)),
                ('address_pt', models.CharField(blank=True, max_length=255)),
                ('phone_primary', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-\\(\\)]{6,20}$')])),
                ('phone_secondary', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-\\(\\)]{6,20}$')])),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL for the Contact page.')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_tet', models.CharField(blank=True, max_length=80)),
                ('name_pt', models.CharField(blank=True, max_length=80)),
                ('description_en', models.TextField(blank=True)),
                ('description_tet', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_coreva_is_acti_aba666_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_tet', models.CharField(blank=True, max_length=120)),
                ('name_pt', models.CharField(blank=True, max_length=120)),
                ('function_en', models.TextField(help_text='Core function')),
                ('function_tet', models.TextField(blank=True)),
                ('function_pt', models.TextField(blank=True)),
                ('value_en', models.TextField(help_text='Strategic value')),
                ('value_tet', models.TextField(blank=True)),
                ('value_pt', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon key, e.g. 'microscope', 'shield', 'graduation'.", max_length=40)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_servic_is_acti_9ee7fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_en', models.CharField(max_length=80)),
                ('label_tet', models.CharField(blank=True, max_length=80)),
                ('label_pt', models.CharField(blank=True, max_length=80)),
                ('value', models.CharField(help_text="e.g. '3', '24/7', '13'", max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_statis_is_acti_6d7f5b_idx')],
            },
        ),
    ]
