# Generated by Django 6.0.6 on 2026-07-06 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Legacy Google Maps embed URL — superseded by the Locations module (Dashboard → Locations).'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_tet', models.CharField(blank=True, max_length=150)),
                ('name_pt', models.CharField(blank=True, max_length=150)),
                ('address_en', models.CharField(max_length=255)),
                ('address_tet', models.CharField(blank=True, max_length=255)),
                ('address_pt', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='e.g. -8.556856', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='e.g. 125.560314', max_digits=9)),
                ('google_maps_url', models.URLField(blank=True, help_text="Optional 'Get Directions' link. If empty, a directions link is built from the coordinates.")),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-\\(\\)]{6,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours_en', models.TextField(blank=True, help_text="One line per entry, e.g. 'Mon–Fri: 08:00–17:00'.")),
                ('opening_hours_tet', models.TextField(blank=True)),
                ('opening_hours_pt', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Main office highlighted first.')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
                'indexes': [models.Index(fields=['is_active', '-is_primary', 'order'], name='core_locati_is_acti_e45c75_idx')],
            },
        ),
    ]
