# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteprofile_map_embed_url_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='supports_appointment',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='If enabled, this service can be booked online through the Appointment module.',
            ),
        ),
    ]
