# Generated by Django 6.0.6 on 2026-07-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicearea_supports_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='show_on_map',
            field=models.BooleanField(db_index=True, default=True, help_text='Show on the homepage/contact page map. Uncheck for non-physical options (e.g. Home Collection) that should still be selectable when booking an appointment.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g. -8.556856. Leave blank for a non-physical option (e.g. Home Collection).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 125.560314. Leave blank for a non-physical option (e.g. Home Collection).', max_digits=9, null=True),
        ),
    ]
