# Generated by Django 6.0.6 on 2026-07-24 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_location_home_collection_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(choices=[('home', 'Home'), ('profile', 'Profile'), ('vision_mission', 'Vision & Mission'), ('programs', 'Programs'), ('structure', 'Team & Structure'), ('news', 'News'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('appointments', 'Book Appointment')], db_index=True, max_length=30, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_tet', models.CharField(blank=True, max_length=200)),
                ('title_pt', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('subtitle_tet', models.CharField(blank=True, max_length=300)),
                ('subtitle_pt', models.CharField(blank=True, max_length=300)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='page_headers/')),
                ('logo', models.ImageField(blank=True, help_text='Optional watermark/logo shown within the header banner.', null=True, upload_to='page_headers/logos/')),
                ('overlay_color', models.CharField(default='#2E1065', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color, e.g. #6D28D9.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=60, help_text='0-100. Applies whether or not a background image is set.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color, e.g. #6D28D9.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('height', models.CharField(choices=[('sm', 'Small (~240px)'), ('md', 'Medium (~360px)'), ('lg', 'Large (~480px)'), ('full', 'Full screen')], default='md', max_length=6)),
                ('show_breadcrumb', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When off, the page falls back to a plain default header.')),
            ],
            options={
                'verbose_name': 'Page Header',
                'ordering': ['page_key'],
            },
        ),
    ]
