# Generated by Django 6.0.6 on 2026-07-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_hero_image_to_pageheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='hero_image',
        ),
    ]
