# Generated by Django 6.0.6 on 2026-07-24 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_siteprofile_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageheader',
            name='overlay_color',
            field=models.CharField(blank=True, default='#2E1065', help_text='Tints the decorative background panel. Leave blank to use the default purple-to-green look.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color, e.g. #6D28D9.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=40, help_text='0-100. Intensity of the decorative background panel.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='text_color',
            field=models.CharField(blank=True, default='', help_text='Overrides the title/breadcrumb color. Leave blank to use the theme default.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color, e.g. #6D28D9.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
