# Generated by Django 6.0.6 on 2026-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pageheader_visual_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageheader',
            name='motto_en',
            field=models.CharField(blank=True, help_text="Short italic line under the title, e.g. 'Saúde diak, ba moris diak'.", max_length=150),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='motto_pt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='motto_tet',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='tagline_en',
            field=models.CharField(blank=True, help_text="Smaller line under the motto, e.g. 'Good health for a good life'.", max_length=150),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='tagline_pt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='tagline_tet',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
