# Generated by Django 6.0.6 on 2026-07-03 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=180)),
                ('title_tet', models.CharField(blank=True, max_length=180)),
                ('title_pt', models.CharField(blank=True, max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_tet', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/')),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-event_date'], name='gallery_alb_is_publ_e3fb87_idx')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('caption_tet', models.CharField(blank=True, max_length=200)),
                ('caption_pt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.album')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['album', 'order'], name='gallery_pho_album_i_d6fe65_idx')],
            },
        ),
    ]
