# Generated by Django 6.0.6

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_servicearea_supports_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[
                    (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'),
                    (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'),
                ])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(
                    default=1,
                    help_text='Maximum number of bookings allowed for this slot on a single date.',
                )),
                ('is_active', models.BooleanField(
                    db_index=True,
                    default=True,
                    help_text='Inactive slots are hidden from booking but keep their history.',
                )),
                ('service_area', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointment_slots',
                    to='core.servicearea',
                )),
            ],
            options={
                'verbose_name': 'Appointment Slot',
                'ordering': ['service_area', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['service_area', 'day_of_week', 'is_active'], name='appt_slot_area_day_active_idx'),
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-\\(\\)]{6,20}$')])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')],
                    db_index=True,
                    default='pending',
                    max_length=20,
                )),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('location', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='appointment_requests',
                    to='core.location',
                )),
                ('slot', models.ForeignKey(
                    help_text='Historical bookings must not lose their slot reference, so slots in use cannot be deleted.',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='appointment_requests',
                    to='appointments.appointmentslot',
                )),
            ],
            options={
                'verbose_name': 'Appointment Request',
                'ordering': ['-appointment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['slot', 'appointment_date', 'status'], name='appt_req_slot_date_status_idx'),
        ),
    ]
