# Generated by Django 6.0.6 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
