# Generated by Django 6.0.6 on 2026-07-03 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_tet', models.CharField(blank=True, max_length=100)),
                ('name_pt', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Program categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_tet', models.CharField(blank=True, max_length=200)),
                ('title_pt', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary_en', models.CharField(blank=True, max_length=300)),
                ('summary_tet', models.CharField(blank=True, max_length=300)),
                ('summary_pt', models.CharField(blank=True, max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_tet', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], db_index=True, default='ongoing', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.programcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-start_date', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'is_featured', '-start_date'], name='programs_pr_is_publ_88b9c5_idx'), models.Index(fields=['is_published', 'status'], name='programs_pr_is_publ_9d2e77_idx')],
            },
        ),
    ]
