# Generated by Django 6.0.6 on 2026-07-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='location',
            new_name='location_en',
        ),
        migrations.AddField(
            model_name='program',
            name='location_pt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='program',
            name='location_tet',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
