# Generated by Django 6.0.6 on 2026-07-03 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_tet', models.CharField(blank=True, max_length=120)),
                ('name_pt', models.CharField(blank=True, max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_tet', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('governance', 'Governance'), ('executive', 'Executive'), ('unit', 'Operational Unit')], db_index=True, default='unit', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='structure.department')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('role_title_en', models.CharField(max_length=150)),
                ('role_title_tet', models.CharField(blank=True, max_length=150)),
                ('role_title_pt', models.CharField(blank=True, max_length=150)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_tet', models.TextField(blank=True)),
                ('bio_pt', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_board_member', models.BooleanField(db_index=True, default=False)),
                ('is_leadership', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='structure.department')),
            ],
            options={
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'category', 'order'], name='structure_d_is_acti_74379d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_published', 'is_board_member', 'order'], name='structure_t_is_publ_fe9d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_published', 'is_leadership', 'order'], name='structure_t_is_publ_5fad76_idx'),
        ),
    ]
